### PR TITLE
Backport dataclasses for Python 3.6

### PR DESCRIPTION
**Pull request by wbarnha**
Thanks for making this library! This should let anyone using Python 3.6 run this.

### CODE REVIEW

**Comment by matejcik** [comment]
Thanks, adding dataclasses is reasonable.

The lockfile update is unnecesarily huge though. I'll see if I can pare it down; there's some magic incantation of poetry that causes updating of only the necessary components.

**Comment by matejcik** [comment]
maybe `poetry lock --no-update` would do it?

**Comment by wbarnha** [comment]
Well that's frustrating... `poetry lock --no-update` doesn't seem to clear things up as much as I'd hoped.

**Comment by matejcik** [comment]
You should first revert all changes to poetry.lock and only then run `poetry lock --no-update`

**Comment by wbarnha** [comment]
> You should first revert all changes to poetry.lock and only then run `poetry lock --no-update`

Funny enough, that's exactly what I did.

**Review by matejcik — APPROVED** [review]
I see. I tried locally and get a similar enough result.

**Pull request merged**
